package com.nahian.mypersonalnotebook.ui

import android.content.Context

internal enum class NotebookLanguage(val preferenceValue: String) {
    ENGLISH("en"),
    BANGLA("bn");

    fun next(): NotebookLanguage = if (this == ENGLISH) BANGLA else ENGLISH

    companion object {
        fun fromPreference(value: String?): NotebookLanguage = if (value == BANGLA.preferenceValue) BANGLA else ENGLISH
    }
}

internal object NotebookLanguageSettings {
    private const val PREFERENCES = "notebook_preferences"
    private const val LANGUAGE_KEY = "language"

    @Volatile
    var current: NotebookLanguage = NotebookLanguage.ENGLISH
        private set

    fun load(context: Context): NotebookLanguage {
        current = NotebookLanguage.fromPreference(
            context.applicationContext.getSharedPreferences(PREFERENCES, Context.MODE_PRIVATE).getString(LANGUAGE_KEY, "en"),
        )
        return current
    }

    fun save(context: Context, language: NotebookLanguage) {
        current = language
        context.applicationContext.getSharedPreferences(PREFERENCES, Context.MODE_PRIVATE)
            .edit()
            .putString(LANGUAGE_KEY, language.preferenceValue)
            .apply()
    }
}

internal fun uiText(english: String): String {
    if (NotebookLanguageSettings.current != NotebookLanguage.BANGLA) return english
    BANGLA_TEXT[english]?.let { return it }
    return when {
        english.startsWith("Reminder saved, but Android did not accept its schedule: ") ->
            "রিমাইন্ডার সংরক্ষণ হয়েছে, তবে Android সময়সূচি গ্রহণ করেনি: " + english.substringAfter("schedule: ")
        english.startsWith("Reminder saved, but it is not registered yet. ") ->
            "রিমাইন্ডার সংরক্ষণ হয়েছে, তবে এখনো নিবন্ধিত হয়নি। " + english.substringAfter("registered yet. ")
        english.startsWith("Reminder is enabled locally but not registered. ") ->
            "রিমাইন্ডারটি ডিভাইসে চালু, তবে নিবন্ধিত নয়। " + english.substringAfter("registered. ")
        english.startsWith("Reminder is off, but Android could not remove its geofence: ") ->
            "রিমাইন্ডার বন্ধ, তবে Android জিওফেন্স সরাতে পারেনি: " + english.substringAfter("geofence: ")
        english.startsWith("Reminder is off, but Android could not remove its old geofence: ") ->
            "রিমাইন্ডার বন্ধ, তবে Android পুরোনো জিওফেন্স সরাতে পারেনি: " + english.substringAfter("geofence: ")
        english.startsWith("Last triggered ") -> "সর্বশেষ চালু: " + english.removePrefix("Last triggered ")
        english.startsWith("Saved ") && english.endsWith(" on this device.") ->
            "${english.removePrefix("Saved ").removeSuffix(" on this device.")} এই ডিভাইসে সংরক্ষিত হয়েছে।"
        else -> english
    }
}

private val BANGLA_TEXT = mapOf(
    "Time reminders" to "সময়ভিত্তিক রিমাইন্ডার",
    "Summary" to "সারসংক্ষেপ",
    "Location Reminders" to "অবস্থানভিত্তিক রিমাইন্ডার",
    "Checklists" to "চেকলিস্ট",
    "Notes" to "নোট",
    "Map" to "মানচিত্র",
    "Test" to "পরীক্ষা",
    "Edit" to "সম্পাদনা",
    "Delete" to "মুছুন",
    "On enter" to "প্রবেশ করলে",
    "On exit" to "বের হলে",
    "Enter or exit" to "প্রবেশ বা বের হলে",
    "Once" to "একবার",
    "Every visit" to "প্রতিবার",
    "Daily" to "প্রতিদিন",
    "Weekly" to "প্রতি সপ্তাহে",
    "Every %d days" to "%d দিন পরপর",
    "Your day, in one place" to "আপনার দিনের সবকিছু এক জায়গায়",
    "A calm place for your notes, plans, and reminders." to "নোট, পরিকল্পনা ও রিমাইন্ডারের জন্য আপনার নিজস্ব জায়গা।",
    "Location reminders" to "অবস্থানভিত্তিক রিমাইন্ডার",
    "No active location reminders" to "কোনো সক্রিয় অবস্থানভিত্তিক রিমাইন্ডার নেই",
    "Time reminders" to "সময়ভিত্তিক রিমাইন্ডার",
    "No scheduled reminders" to "কোনো নির্ধারিত রিমাইন্ডার নেই",
    "Checklists" to "চেকলিস্ট",
    "Notebook" to "নোটবুক",
    "Notes" to "নোট",
    "Recent notes" to "সাম্প্রতিক নোট",
    "Your saved notes will appear here." to "আপনার সংরক্ষিত নোট এখানে দেখা যাবে।",
    "Your checklists are saved on this device." to "আপনার চেকলিস্ট এই ডিভাইসে সংরক্ষিত থাকে।",
    "Your notebook is ready" to "আপনার নোটবুক প্রস্তুত",
    "Create a note; it will be saved on this device." to "একটি নোট তৈরি করুন; এটি এই ডিভাইসে সংরক্ষিত হবে।",
    "Create first note" to "প্রথম নোট তৈরি করুন",
    "Create first checklist" to "প্রথম চেকলিস্ট তৈরি করুন",
    "Create first reminder" to "প্রথম রিমাইন্ডার তৈরি করুন",
    "Nothing scheduled yet" to "এখনো কিছু নির্ধারণ করা হয়নি",
    "Choose a date and time; Android will notify you then." to "তারিখ ও সময় বেছে নিন; তখন Android আপনাকে জানাবে।",
    "New reminder" to "নতুন রিমাইন্ডার",
    "New time reminder" to "নতুন সময়ভিত্তিক রিমাইন্ডার",
    "Edit time reminder" to "সময়ভিত্তিক রিমাইন্ডার সম্পাদনা",
    "New note" to "নতুন নোট",
    "Edit note" to "নোট সম্পাদনা",
    "Write your note" to "আপনার নোট লিখুন",
    "New checklist" to "নতুন চেকলিস্ট",
    "Checklist name" to "চেকলিস্টের নাম",
    "Add an item" to "একটি আইটেম যোগ করুন",
    "Add" to "যোগ করুন",
    "Create" to "তৈরি করুন",
    "Title" to "শিরোনাম",
    "Reminder title / location name" to "রিমাইন্ডারের শিরোনাম / স্থানের নাম",
    "Reminder message" to "রিমাইন্ডারের বার্তা",
    "Save" to "সংরক্ষণ",
    "Save reminder" to "রিমাইন্ডার সংরক্ষণ",
    "Cancel" to "বাতিল",
    "Delete" to "মুছুন",
    "Edit" to "সম্পাদনা",
    "Done" to "সম্পন্ন",
    "Delete this note?" to "এই নোটটি মুছবেন?",
    "Delete checklist?" to "চেকলিস্টটি মুছবেন?",
    "Delete reminder?" to "রিমাইন্ডারটি মুছবেন?",
    "This removes the note from this device." to "এতে এই ডিভাইস থেকে নোটটি মুছে যাবে।",
    "The list and its items will be removed from this device." to "তালিকা ও এর আইটেমগুলো এই ডিভাইস থেকে মুছে যাবে।",
    "Nothing pinned to a place yet" to "এখনো কোনো স্থানের সঙ্গে রিমাইন্ডার যুক্ত নেই",
    "At the right place, at the right time" to "সঠিক স্থানে, সঠিক সময়ে",
    "A useful nudge, right where you need it." to "যেখানে দরকার, সেখানেই ছোট্ট মনে করিয়ে দেওয়া।",
    "Set a location, radius, trigger, and message. Android will notify you when the geofence transition happens." to "স্থান, ব্যাসার্ধ, ট্রিগার ও বার্তা নির্ধারণ করুন। জিওফেন্সে প্রবেশ বা বের হলে Android আপনাকে জানাবে।",
    "A system geofence, not background GPS tracking" to "সিস্টেম জিওফেন্স ব্যবহার করা হয়, ব্যাকগ্রাউন্ড GPS ট্র্যাকিং নয়",
    "No continuous GPS tracking" to "অবিরাম GPS ট্র্যাকিং নেই",
    "Pick once; Android monitors the geofence" to "একবার স্থান বেছে নিন; Android জিওফেন্স পর্যবেক্ষণ করবে",
    "Choose a saved place or save your current selection for later." to "সংরক্ষিত স্থান বেছে নিন অথবা বর্তমান নির্বাচনটি পরে ব্যবহারের জন্য সংরক্ষণ করুন।",
    "Saved on this device" to "এই ডিভাইসে সংরক্ষিত",
    "No saved locations yet." to "এখনো কোনো স্থান সংরক্ষিত নেই।",
    "Get current location" to "বর্তমান অবস্থান নিন",
    "Use your current location" to "বর্তমান অবস্থান ব্যবহার করুন",
    "Search places" to "স্থান খুঁজুন",
    "Search" to "খুঁজুন",
    "Search by address, business, or landmark" to "ঠিকানা, প্রতিষ্ঠান বা পরিচিত স্থানের নাম দিয়ে খুঁজুন",
    "Clear" to "মুছুন",
    "Save selected location" to "নির্বাচিত স্থান সংরক্ষণ করুন",
    "Name this saved location" to "সংরক্ষিত স্থানের নাম দিন",
    "Settings" to "সেটিংস",
    "Reminder active" to "রিমাইন্ডার সক্রিয়",
    "Turn this off to keep it saved without registering a geofence." to "জিওফেন্স চালু না রেখে শুধু সংরক্ষণ করতে এটি বন্ধ করুন।",
    "Repeat every (days)" to "কত দিন পরপর পুনরাবৃত্তি হবে",
    "Choose 1–365 days. The app checks recurrence only when Android delivers a geofence transition." to "১–৩৬৫ দিন বেছে নিন। Android জিওফেন্স ট্রানজিশন জানালে অ্যাপ পুনরাবৃত্তি যাচাই করে।",
    "Android's geofence is low-power; some manufacturers still restrict background delivery." to "Android-এর জিওফেন্স কম শক্তি ব্যবহার করে; কিছু ফোন নির্মাতা ব্যাকগ্রাউন্ডে নোটিফিকেশন সীমিত করতে পারে।",
    "Battery restrictions may delay alerts" to "ব্যাটারি সীমাবদ্ধতায় সতর্কবার্তা দেরি হতে পারে",
    "Some reminders need attention" to "কিছু রিমাইন্ডারে মনোযোগ দরকার",
    "Open or edit a reminder to see why it could not be registered." to "কেন রেজিস্টার হয়নি জানতে রিমাইন্ডার খুলুন বা সম্পাদনা করুন।",
    "Not now" to "এখন নয়",
    "Open alarm settings" to "অ্যালার্ম সেটিংস খুলুন",
    "Allow exact alarms" to "নির্দিষ্ট সময়ের অ্যালার্ম অনুমোদন করুন",
    "Android needs this permission to alert close to the time you set." to "নির্ধারিত সময়ের কাছাকাছি সতর্ক করতে Android-এর এই অনুমতি প্রয়োজন।",
    "Allow reminder notifications" to "রিমাইন্ডার নোটিফিকেশন অনুমোদন করুন",
    "Android will not display an alert while notifications are blocked." to "নোটিফিকেশন বন্ধ থাকলে Android সতর্কবার্তা দেখাবে না।",
    "Allow notifications" to "নোটিফিকেশন অনুমোদন করুন",
    "This creates a one-time notification. Android may delay it if exact-alarm access or notifications are turned off." to "এটি একবারের নোটিফিকেশন তৈরি করে। নির্দিষ্ট অ্যালার্মের অনুমতি বা নোটিফিকেশন বন্ধ থাকলে Android দেরি করতে পারে।",
    "Your reminders" to "আপনার রিমাইন্ডার",
    "Back to summary" to "সারসংক্ষেপে ফিরুন",
    "Selected" to "নির্বাচিত",
    "Choose date" to "তারিখ বেছে নিন",
    "Choose time" to "সময় বেছে নিন",
    "Create a checklist and add items you can tick off." to "একটি চেকলিস্ট তৈরি করে টিক দেওয়ার মতো আইটেম যোগ করুন।",
    "Your notes stay on this device." to "আপনার নোট এই ডিভাইসেই থাকবে।",
    "Make a list you can check off" to "টিক দিয়ে সম্পন্ন করার মতো তালিকা তৈরি করুন",
    "e.g. Alpha Clothing Ltd." to "যেমন: Alpha Clothing Ltd.",
    "e.g. Packing Report জমা দিতে হবে" to "যেমন: প্যাকিং রিপোর্ট জমা দিতে হবে",
    "Choose a location" to "একটি স্থান বেছে নিন",
    "Selected location" to "নির্বাচিত স্থান",
    "Done viewing map" to "মানচিত্র দেখা শেষ",
    "Use this location" to "এই স্থান ব্যবহার করুন",
    "Choose location" to "স্থান বেছে নিন",
    "Change / view on map" to "মানচিত্রে পরিবর্তন / দেখুন",
    "Tap the map to preview a point. Map tiles need internet." to "একটি স্থান দেখতে মানচিত্রে ট্যাপ করুন। মানচিত্রের জন্য ইন্টারনেট দরকার।",
    "Tap the map once to choose the geofence center; it will return to the form. Map tiles need internet." to "জিওফেন্সের কেন্দ্র বেছে নিতে মানচিত্রে একবার ট্যাপ করুন; এটি ফর্মে ফিরবে। মানচিত্রের জন্য ইন্টারনেট দরকার।",
    "Geofences are monitored by Android / Google Play services. Location reminders can work without mobile data after registration, but map tiles and place search need a network." to "জিওফেন্স Android / Google Play services পর্যবেক্ষণ করে। নিবন্ধনের পর মোবাইল ডেটা ছাড়াও অবস্থানভিত্তিক রিমাইন্ডার কাজ করতে পারে, তবে মানচিত্র ও স্থান খুঁজতে নেটওয়ার্ক দরকার।",
    "Create a place-based reminder to get started." to "শুরু করতে একটি স্থানভিত্তিক রিমাইন্ডার তৈরি করুন।",
    "Registered with Android" to "Android-এ নিবন্ধিত",
    "Needs attention" to "মনোযোগ প্রয়োজন",
    "Disabled" to "বন্ধ",
    "Last triggered: never" to "সর্বশেষ চালু: কখনো নয়",
    "Back" to "ফিরে যান",
    "Untitled note" to "শিরোনামহীন নোট",
    "Edit location reminder" to "অবস্থানভিত্তিক রিমাইন্ডার সম্পাদনা",
    "New location reminder" to "নতুন অবস্থানভিত্তিক রিমাইন্ডার",
    "Last triggered: never" to "সর্বশেষ চালু: কখনো নয়",
    "Create location reminder" to "অবস্থানভিত্তিক রিমাইন্ডার তৈরি করুন",
    "Back to summary" to "সারসংক্ষেপে ফিরুন",
    "Open battery settings" to "ব্যাটারি সেটিংস খুলুন",
    "Open notification settings" to "নোটিফিকেশন সেটিংস খুলুন",
    "Geofences are monitored by Android / Google Play services. Location reminders can work without mobile data after registration, but map tiles and place search need a network." to "জিওফেন্স Android / Google Play services পর্যবেক্ষণ করে। নিবন্ধনের পর মোবাইল ডেটা ছাড়াও অবস্থানভিত্তিক রিমাইন্ডার কাজ করতে পারে, তবে মানচিত্র ও স্থান খুঁজতে নেটওয়ার্ক দরকার।",
    "Create a place-based reminder to get started." to "শুরু করতে একটি স্থানভিত্তিক রিমাইন্ডার তৈরি করুন।",
    "Registered with Android" to "Android-এ নিবন্ধিত",
    "Needs attention" to "মনোযোগ প্রয়োজন",
    "Disabled" to "বন্ধ",
    "On enter" to "প্রবেশ করলে",
    "On exit" to "বের হলে",
    "Enter or exit" to "প্রবেশ বা বের হলে",
    "Map" to "মানচিত্র",
    "Test" to "পরীক্ষা",
    "Edit" to "সম্পাদনা",
    "Once" to "একবার",
    "Every visit" to "প্রতিবার",
    "Daily" to "প্রতিদিন",
    "Weekly" to "প্রতি সপ্তাহে",
    "New checklist" to "নতুন চেকলিস্ট",
    "No notification permission" to "নোটিফিকেশনের অনুমতি নেই",
    "No saved locations yet." to "এখনো কোনো স্থান সংরক্ষিত নেই।",
    "Title" to "শিরোনাম",
    "Save" to "সংরক্ষণ",
    "Delete" to "মুছুন",
    "Cancel" to "বাতিল",
    "Continue" to "চালিয়ে যান",
    "Open app settings" to "অ্যাপ সেটিংস খুলুন",
    "Allow all the time" to "সব সময় অনুমতি দিন",
    "Open location settings" to "অবস্থান সেটিংস খুলুন",
    "Notification permission is blocked" to "নোটিফিকেশনের অনুমতি বন্ধ",
    "Enable notifications for NAHIAN'S NOTEBOOK in Android settings. Android will not show another permission prompt after repeated denials." to "Android সেটিংসে NAHIAN'S NOTEBOOK-এর নোটিফিকেশন চালু করুন। বারবার অস্বীকার করলে Android আর অনুমতির অনুরোধ দেখাবে না।",
    "Allow reminder notifications" to "রিমাইন্ডার নোটিফিকেশন অনুমোদন করুন",
    "Android needs notification permission to show geofence alerts, including when the app is closed." to "অ্যাপ বন্ধ থাকলেও জিওফেন্স সতর্কবার্তা দেখাতে Android-এর নোটিফিকেশন অনুমতি দরকার।",
    "Notifications are turned off" to "নোটিফিকেশন বন্ধ আছে",
    "Turn on notifications for NAHIAN'S NOTEBOOK in Android settings. A geofence cannot show its alert while notifications are blocked." to "Android সেটিংসে NAHIAN'S NOTEBOOK-এর নোটিফিকেশন চালু করুন। নোটিফিকেশন বন্ধ থাকলে জিওফেন্স সতর্কবার্তা দেখাতে পারবে না।",
    "Location reminder channel is blocked" to "অবস্থানভিত্তিক রিমাইন্ডার চ্যানেল বন্ধ",
    "Enable the Location reminders notification channel in Android settings." to "Android সেটিংসে Location reminders নোটিফিকেশন চ্যানেল চালু করুন।",
    "Allow location access all the time" to "সব সময় অবস্থান ব্যবহারের অনুমতি দিন",
    "Background location is used only by Android's registered geofence. This app does not continuously track GPS. Android 10 asks for this separately after foreground location." to "ব্যাকগ্রাউন্ড অবস্থান শুধু Android-এর নিবন্ধিত জিওফেন্স ব্যবহার করে। অ্যাপ অবিরাম GPS ট্র্যাক করে না। Android 10-এ সামনের অবস্থান অনুমতির পরে এটি আলাদাভাবে চাওয়া হয়।",
    "For reminders to work while the app is closed, open App permissions → Location and choose “Allow all the time”. This is required by Android for background geofencing." to "অ্যাপ বন্ধ থাকলেও রিমাইন্ডার চালাতে App permissions → Location খুলে “Allow all the time” বেছে নিন। ব্যাকগ্রাউন্ড জিওফেন্সের জন্য Android এটি বাধ্যতামূলক করেছে।",
    "Google Play services unavailable" to "Google Play services পাওয়া যাচ্ছে না",
    "Android GeofencingClient needs Google Play services for location. Update or enable Google Play services, then try again." to "Android GeofencingClient-এর অবস্থানের জন্য Google Play services দরকার। Google Play services হালনাগাদ বা চালু করে আবার চেষ্টা করুন।",
    "Precise location permission is blocked" to "নির্ভুল অবস্থানের অনুমতি বন্ধ",
    "Enable Precise location in this app's Android permissions. Location reminders need precise coordinates to monitor the selected radius." to "Android অ্যাপ অনুমতিতে Precise location চালু করুন। নির্বাচিত ব্যাসার্ধ পর্যবেক্ষণে অবস্থানভিত্তিক রিমাইন্ডারের নির্ভুল স্থানাঙ্ক দরকার।",
    "Allow precise location" to "নির্ভুল অবস্থানের অনুমতি দিন",
    "Precise location is used to select a place and register Android geofences. The app does not poll or continuously track your GPS." to "স্থান বেছে নিতে ও Android জিওফেন্স নিবন্ধনে নির্ভুল অবস্থান ব্যবহৃত হয়। অ্যাপ GPS বারবার পরীক্ষা বা অবিরাম ট্র্যাক করে না।",
    "Turn on device location" to "ডিভাইসের অবস্থান চালু করুন",
    "Android location services are currently off. Turn them on so the system can detect geofence entry and exit." to "Android-এর অবস্থান সেবা বন্ধ আছে। জিওফেন্সে প্রবেশ ও বের হওয়া শনাক্ত করতে এটি চালু করুন।",
    "Open notification settings" to "নোটিফিকেশন সেটিংস খুলুন",
    "Open app settings" to "অ্যাপ সেটিংস খুলুন",
    "Open location settings" to "অবস্থান সেটিংস খুলুন",
    "Open battery settings" to "ব্যাটারি সেটিংস খুলুন",
    "Notifications are turned off for NAHIAN'S NOTEBOOK. Enable them in Android settings." to "Android সেটিংসে NAHIAN'S NOTEBOOK-এর নোটিফিকেশন চালু করুন।",
    "Allow notifications so scheduled reminders can alert you." to "নির্ধারিত রিমাইন্ডার পেতে নোটিফিকেশন অনুমোদন করুন।",
    "Notifications allowed." to "নোটিফিকেশন অনুমোদিত হয়েছে।",
    "Allow notifications in Android settings to receive reminders." to "রিমাইন্ডার পেতে Android সেটিংসে নোটিফিকেশন চালু করুন।",
    "Choose a future date and time." to "ভবিষ্যতের তারিখ ও সময় বেছে নিন।",
    "Choose a new future time before enabling this reminder." to "এই রিমাইন্ডার চালু করার আগে নতুন ভবিষ্যৎ সময় বেছে নিন।",
    "Add a title for this reminder." to "এই রিমাইন্ডারের শিরোনাম লিখুন।",
    "Add a reminder message." to "রিমাইন্ডারের বার্তা লিখুন।",
    "Choose location before saving." to "সংরক্ষণের আগে স্থান বেছে নিন।",
    "Write a title or some note text first." to "আগে একটি শিরোনাম বা নোট লিখুন।",
    "Give the checklist a name." to "চেকলিস্টের একটি নাম দিন।",
    "Write a checklist item first." to "আগে একটি চেকলিস্ট আইটেম লিখুন।",
    "This checklist no longer exists." to "এই চেকলিস্টটি আর নেই।",
    "This reminder is disabled." to "এই রিমাইন্ডারটি বন্ধ আছে।",
    "This reminder no longer exists." to "এই রিমাইন্ডারটি আর নেই।",
    "Please allow exact alarms for NAHIAN'S NOTEBOOK in Android settings, then try again." to "Android সেটিংসে NAHIAN'S NOTEBOOK-এর নির্দিষ্ট অ্যালার্ম অনুমোদন করে আবার চেষ্টা করুন।",
    "Allow exact alarms for NAHIAN'S NOTEBOOK in Android settings, then save again." to "Android সেটিংসে NAHIAN'S NOTEBOOK-এর নির্দিষ্ট অ্যালার্ম অনুমোদন করে আবার সংরক্ষণ করুন।",
    "Android denied exact alarm access. Enable Alarms & reminders in app settings." to "Android নির্দিষ্ট অ্যালার্মের অনুমতি দেয়নি। অ্যাপ সেটিংসে Alarms & reminders চালু করুন।",
    "Android could not show the alert. Check notification permission and channel settings." to "Android সতর্কবার্তা দেখাতে পারেনি। নোটিফিকেশন অনুমতি ও চ্যানেল সেটিংস দেখুন।",
    "Current" to "বর্তমান",
    "Saved" to "সংরক্ষিত",
    "Reminders" to "রিমাইন্ডার",
    "Location Reminder" to "অবস্থানভিত্তিক রিমাইন্ডার",
    "Scheduled reminder" to "নির্ধারিত রিমাইন্ডার",
    "Scheduled reminders" to "নির্ধারিত রিমাইন্ডার",
    "Notifications for reminders scheduled by date and time" to "তারিখ ও সময় অনুযায়ী নির্ধারিত রিমাইন্ডারের নোটিফিকেশন",
    "Snooze 10 min" to "১০ মিনিট পিছিয়ে দিন",
    "Open" to "খুলুন",
    "Alerts when you enter or leave places you selected" to "নির্বাচিত স্থানে প্রবেশ বা বের হলে সতর্কবার্তা",
    "Test notification · " to "পরীক্ষামূলক নোটিফিকেশন · ",
    "No matching places were found. Try a fuller address or use the map." to "মিল থাকা কোনো স্থান পাওয়া যায়নি। সম্পূর্ণ ঠিকানা লিখুন অথবা মানচিত্র ব্যবহার করুন।",
    "Enter a place, address, or landmark to search." to "খোঁজার জন্য স্থানের নাম, ঠিকানা বা পরিচিত স্থান লিখুন।",
    "Search is unavailable right now. You can still choose a point on the map." to "এখন খোঁজা যাচ্ছে না। তবু মানচিত্রে একটি স্থান বেছে নিতে পারেন।",
    "Place search is not available on this device. Use the map instead." to "এই ডিভাইসে স্থান খোঁজা যাচ্ছে না। এর বদলে মানচিত্র ব্যবহার করুন।",
    "Could not get the current location. Turn on Location and try again." to "বর্তমান অবস্থান পাওয়া যায়নি। Location চালু করে আবার চেষ্টা করুন।",
    "Could not get a location fix. Check that Location is on and try again." to "অবস্থানের তথ্য পাওয়া যায়নি। Location চালু আছে কি না দেখে আবার চেষ্টা করুন।",
    "Choose a current, map, or search result first." to "আগে বর্তমান অবস্থান, মানচিত্র বা খোঁজার ফলাফল থেকে একটি স্থান বেছে নিন।",
    "Give this saved location a name." to "এই সংরক্ষিত স্থানের একটি নাম দিন।",
    "The device returned invalid coordinates." to "ডিভাইসটি ভুল স্থানাঙ্ক দিয়েছে।",
    "Those coordinates are invalid." to "এই স্থানাঙ্কগুলো সঠিক নয়।",
    "Choose a location before saving." to "সংরক্ষণের আগে একটি স্থান বেছে নিন।",
    "Choose a future date and time." to "ভবিষ্যতের তারিখ ও সময় বেছে নিন।",
    "Choose a new future time before enabling this reminder." to "এই রিমাইন্ডার চালু করার আগে নতুন ভবিষ্যৎ সময় বেছে নিন।",
    "Choose a radius of 100 m, 200 m, 500 m, or 1 km." to "১০০ মি, ২০০ মি, ৫০০ মি বা ১ কিমি ব্যাসার্ধ বেছে নিন।",
    "Choose a valid geofence trigger." to "সঠিক জিওফেন্স ট্রিগার বেছে নিন।",
    "Choose a valid recurrence." to "সঠিক পুনরাবৃত্তির ধরন বেছে নিন।",
    "Custom recurrence must be between 1 and 365 days." to "কাস্টম পুনরাবৃত্তি ১ থেকে ৩৬৫ দিনের মধ্যে হতে হবে।",
    "Give the checklist a name." to "চেকলিস্টের একটি নাম দিন।",
    "Write a checklist item first." to "আগে একটি চেকলিস্ট আইটেম লিখুন।",
    "Write a title or some note text first." to "আগে একটি শিরোনাম বা নোট লিখুন।",
    "This checklist no longer exists." to "এই চেকলিস্টটি আর নেই।",
    "This reminder is disabled." to "এই রিমাইন্ডারটি বন্ধ আছে।",
    "This reminder no longer exists." to "এই রিমাইন্ডারটি আর নেই।",
    "A single current-location fix is used to set the geofence. No continuous GPS tracking is started." to "জিওফেন্স নির্ধারণে বর্তমান অবস্থানের একবারের তথ্য নেওয়া হয়। অবিরাম GPS ট্র্যাকিং চালু হয় না।",
    "Location services are off. Turn on device location to register geofences." to "অবস্থানের সেবা বন্ধ। জিওফেন্স নিবন্ধন করতে ডিভাইসের অবস্থান চালু করুন।",
    "Precise location permission is required to monitor this geofence." to "এই জিওফেন্স পর্যবেক্ষণে নির্ভুল অবস্থানের অনুমতি দরকার।",
    "Precise location permission was denied. Allow it and try again." to "নির্ভুল অবস্থানের অনুমতি দেওয়া হয়নি। অনুমতি দিয়ে আবার চেষ্টা করুন।",
    "Android supports at most %d active geofences per app." to "প্রতি অ্যাপে Android সর্বোচ্চ %dটি সক্রিয় জিওফেন্স সমর্থন করে।",
    "Saved location added on this device." to "সংরক্ষিত স্থানটি এই ডিভাইসে যোগ করা হয়েছে।",
    "Saved location deleted." to "সংরক্ষিত স্থান মুছে ফেলা হয়েছে।",
    "Reminder deleted." to "রিমাইন্ডার মুছে ফেলা হয়েছে।",
    "Reminder updated." to "রিমাইন্ডার হালনাগাদ করা হয়েছে।",
    "Open Android Settings and update this app's permissions." to "Android সেটিংস খুলে এই অ্যাপের অনুমতি হালনাগাদ করুন।",
    "Open Android Settings → Apps → NAHIAN'S NOTEBOOK → Battery." to "Android সেটিংস → Apps → NAHIAN'S NOTEBOOK → Battery খুলুন।",
    "This checklist no longer exists." to "এই চেকলিস্টটি আর নেই।",
    "This reminder no longer exists." to "এই রিমাইন্ডারটি আর নেই।",
    "This removes the note from this device." to "এতে এই ডিভাইস থেকে নোটটি মুছে যাবে।",
    "The list and its items will be removed from this device." to "তালিকা ও এর আইটেমগুলো এই ডিভাইস থেকে মুছে যাবে।",
    "Allow notifications in Android settings to receive reminders." to "রিমাইন্ডার পেতে Android সেটিংসে নোটিফিকেশন চালু করুন।",
    "Notifications allowed." to "নোটিফিকেশন অনুমোদিত হয়েছে।",
    "Last triggered: never" to "সর্বশেষ চালু: কখনো নয়",
    "Reminder saved and registered with Android." to "রিমাইন্ডার সংরক্ষণ করে Android-এ নিবন্ধন করা হয়েছে।",
    "Reminder saved as disabled." to "রিমাইন্ডার বন্ধ অবস্থায় সংরক্ষণ করা হয়েছে.",
    "You have %d scheduled and %d active location reminders, with %d checklist items left." to "আপনার %dটি নির্ধারিত ও %dটি সক্রিয় অবস্থানভিত্তিক রিমাইন্ডার আছে; চেকলিস্টে %dটি আইটেম বাকি।",
    "%d scheduled reminders" to "%dটি নির্ধারিত রিমাইন্ডার",
    "%d lists · %d items remaining" to "%dটি তালিকা · %dটি আইটেম বাকি",
    "%d recent notes shown below" to "নিচে %dটি সাম্প্রতিক নোট",
    "Your notes and reminders" to "আপনার নোট ও রিমাইন্ডার",

    "Location permission required" to "অবস্থানের অনুমতি প্রয়োজন",
    "Allow precise location to choose a current location." to "বর্তমান অবস্থান বেছে নিতে নির্ভুল অবস্থানের অনুমতি দিন।",
    "Android notification permission is needed to test this reminder." to "এই রিমাইন্ডার পরীক্ষা করতে Android-এর নোটিফিকেশন অনুমতি দরকার।",
    "Enable notifications for NAHIAN'S NOTEBOOK in Android settings." to "Android সেটিংসে NAHIAN'S NOTEBOOK-এর নোটিফিকেশন চালু করুন।",
    "Enable notifications for NAHIAN'S NOTEBOOK in Android settings, then test again." to "Android সেটিংসে NAHIAN'S NOTEBOOK-এর নোটিফিকেশন চালু করে আবার পরীক্ষা করুন।",
    "Location reminders are blocked" to "অবস্থানভিত্তিক রিমাইন্ডার বন্ধ",
    "Allow notifications so Android can show location reminder alerts." to "Android যেন অবস্থানভিত্তিক সতর্কবার্তা দেখাতে পারে, সে জন্য নোটিফিকেশন অনুমোদন করুন।",
    "Notifications are turned off for NAHIAN'S NOTEBOOK. Enable them in Android settings." to "Android সেটিংসে NAHIAN'S NOTEBOOK-এর নোটিফিকেশন চালু করুন।",
    "The Location reminders notification channel is blocked. Enable it in Android settings." to "Android সেটিংসে Location reminders নোটিফিকেশন চ্যানেল চালু করুন।",
    "The Scheduled reminders notification channel is blocked. Enable it in Android settings." to "Android সেটিংসে Scheduled reminders নোটিফিকেশন চ্যানেল চালু করুন।",
    "Android allows up to 100 active geofences per app." to "প্রতি অ্যাপে Android সর্বোচ্চ ১০০টি সক্রিয় জিওফেন্স অনুমোদন করে।",
    "Android supports at most 100 active geofences per app." to "প্রতি অ্যাপে Android সর্বোচ্চ ১০০টি সক্রিয় জিওফেন্স সমর্থন করে।",
    "The selected latitude is invalid. Choose the location again." to "নির্বাচিত অক্ষাংশ সঠিক নয়। স্থানটি আবার বেছে নিন।",
    "The selected longitude is invalid. Choose the location again." to "নির্বাচিত দ্রাঘিমাংশ সঠিক নয়। স্থানটি আবার বেছে নিন।",
    "The saved coordinates are invalid. Edit the reminder and choose a location again." to "সংরক্ষিত স্থানাঙ্ক সঠিক নয়। রিমাইন্ডার সম্পাদনা করে আবার স্থান বেছে নিন।",
    "The saved geofence radius is invalid. Choose 100 m, 200 m, 500 m, or 1 km." to "সংরক্ষিত জিওফেন্স ব্যাসার্ধ সঠিক নয়। ১০০ মি, ২০০ মি, ৫০০ মি বা ১ কিমি বেছে নিন।",
    "The saved trigger type is invalid. Edit this reminder." to "সংরক্ষিত ট্রিগারের ধরন সঠিক নয়। এই রিমাইন্ডার সম্পাদনা করুন।",
    "The saved recurrence is invalid. Edit this reminder." to "সংরক্ষিত পুনরাবৃত্তির ধরন সঠিক নয়। এই রিমাইন্ডার সম্পাদনা করুন।",
    "The saved custom recurrence is invalid. Edit this reminder." to "সংরক্ষিত কাস্টম পুনরাবৃত্তি সঠিক নয়। এই রিমাইন্ডার সম্পাদনা করুন।",
    "Duplicate geofence ID found in local data; edit this reminder to repair it." to "স্থানীয় ডেটায় একই জিওফেন্স আইডি পাওয়া গেছে; ঠিক করতে এই রিমাইন্ডার সম্পাদনা করুন।",
    "A larger radius can improve reliability in dense areas." to "ঘনবসতিপূর্ণ এলাকায় বড় ব্যাসার্ধ বেশি নির্ভরযোগ্য হতে পারে।",
    "Location reminders need precise coordinates to monitor the selected radius." to "নির্বাচিত ব্যাসার্ধ পর্যবেক্ষণে অবস্থানভিত্তিক রিমাইন্ডারের নির্ভুল স্থানাঙ্ক দরকার।",
    "Open Android Settings and update this app's permissions." to "Android সেটিংস খুলে এই অ্যাপের অনুমতি হালনাগাদ করুন।",
    "Open Android Settings → Apps → NAHIAN'S NOTEBOOK → Battery." to "Android সেটিংস → Apps → NAHIAN'S NOTEBOOK → Battery খুলুন।",
    "Reminder saved and registered with Android." to "রিমাইন্ডার সংরক্ষণ করে Android-এ নিবন্ধন করা হয়েছে।",
    "Reminder saved as disabled." to "রিমাইন্ডার বন্ধ অবস্থায় সংরক্ষণ করা হয়েছে।",
    "Reminder deleted." to "রিমাইন্ডার মুছে ফেলা হয়েছে।",
    "Reminder updated." to "রিমাইন্ডার হালনাগাদ করা হয়েছে।",
)
